name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Copy files via SSH
        run: scp -r -o StrictHostKeyChecking=no ./* ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/var/www/droplet_test

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            # Navigate to the deployment directory
            cd /var/www/droplet_test

            # Optionally, set permissions for the web server
            sudo chown -R www-data:www-data /var/www/droplet_test
            sudo find /var/www/droplet_test -type d -exec chmod 755 {} \;
            sudo find /var/www/droplet_test -type f -exec chmod 644 {} \;

            # Any necessary post-deployment tasks, such as restarting the web server
            sudo systemctl restart nginx

          EOF
